apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    release: monitoring
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack    
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - demo-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
