apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: demo-app
spec:
  metrics:
  - name: error-rate
    interval: 1m
    successCondition: result[0] < 0.05  # Menos del 5% de errores
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local 
        query: |
          sum(rate(http_requests_total{status=~"5.*",app="tu-app"}[1m])) 
          / 
          sum(rate(http_requests_total{app="tu-app"}[1m]))