# Archivo: k8s/base/backend/analysis-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: demo-app
spec:
  metrics:
  - name: error-rate-check
    interval: 30s # Revisamos cada 30s (2 ciclos de scrape de Prometheus)
    successCondition: result[0] < 0.05
    failureLimit: 2
    provider:
      prometheus:
        address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{app="backend", namespace="demo-app", status=~"5.*"}[1m])) 
          / 
          (sum(rate(http_requests_total{app="backend", namespace="demo-app"}[1m])) + 0.001)