apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-json-files
data:
  config.json: |
    {
      "server": {
        "port": 3000
      }
    }
  settings.json: |
    {
      "featureFlags": {
        "demoMode": true
      }
    }
