apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false

      initContainers:
        - name: init-backend-data
          image: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "InitContainer: comprobando inicialización del volumen..."
              if [ -f /data/empresa.json ]; then
                echo "Datos ya inicializados. No se copian archivos."
              else
                echo "Copiando datos iniciales al PVC..."
                cp /app/src/data/empresa.json /data/
                cp /app/src/data/facturas.json /data/
                cp /app/src/data/productos.json /data/
                cp /app/src/data/productos.test.json /data/
                echo "Archivos copiados:"
                ls -l /data
              fi
          volumeMounts:
            - name: backend-data
              mountPath: /data

      containers:
        - name: backend
          image: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: DATA_DIR
              value: /app/data
            - name: PORT
              value: "3000"
            - name: API_BASE_URL
              value: "http://demo.local"
          volumeMounts:
            - name: backend-data
              mountPath: /app/data
          resources:
            requests:
              cpu: "250m"       # Solicita 0.25 CPU
              memory: "256Mi"   # Solicita 256 MiB de memoria
            limits:
              cpu: "500m"       # Límite de 0.5 CPU
              memory: "512Mi"   # Límite de 512 MiB de memoria

      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: backend-data-pvc
