apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:

      # ==============================
      # InitContainer: inicializa el PVC
      # ==============================
      initContainers:
      - name: init-backend-data
        image: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "InitContainer: comprobando volumen persistente..."
            if [ "$(ls -A /data 2>/dev/null)" ]; then
              echo "El volumen ya contiene datos. No se copian archivos."
            else
              echo "Volumen vacío. Copiando datos iniciales desde /app/src/data..."
              cp -r /app/src/data/* /data/
              echo "Datos copiados:"
              ls -l /data
            fi
        volumeMounts:
        - name: backend-data
          mountPath: /data

      # ==============================
      # Contenedor principal
      # ==============================
      containers:
      - name: backend
        image: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend:latest
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 3000

        env:
        - name: DATA_DIR
          value: /app/data
        - name: PORT
          value: "3000"

        volumeMounts:
        - name: backend-data
          mountPath: /app/data

      # ==============================
      # Volúmenes
      # ==============================
      volumes:
      - name: backend-data
        persistentVolumeClaim:
          claimName: backend-data-pvc
