apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
- rollout.yaml
- service.yaml
- configmap.yaml
- pvc-backend-data.yaml
images:
- digest: sha256:408aa679b00de301b83e2c65f61fc3b1788e2031689bc8ff5d2eebc61e30652f
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
