apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc-backend-data.yaml

images:
- digest: sha256:b719b9560a4b99861a4f0005c712567f80c84505572e07dc496ae8d302a30da2
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
