apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- rollout.yaml
- service.yaml
- configmap.yaml
- pvc-backend-data.yaml

images:
- digest: sha256:729e7c5c1dfce88d3e1809e645eb56bd1e113a550b2c46ed8017d307f843c785
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
