apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc-backend-data.yaml

images:
- digest: sha256:ff2f2c5d5b241f92f28e5029b37958a6725a26210425acb49fe651388daf1afc
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
