apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:a4687d85b29a7505056e79f298525b87965a578cd0ccd70c93ea04fbdd86b1f8
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:3a4d2f9078c621fbef9256261e170bd7461323abf4991c7cf615446dd567bc10
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
