apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:bed2c7bcb58e20c7ab2cbe07db4ecef582d6b299b119f8aaa7c35464fadf4f70
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:3999e2974dd27d6bc945ba38c0685b811f0a5ed83d8ce18d65c20bc54ad3f3fa
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
