apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:75712f826931dbcc524d3e49c7f2db2aee131705ffcb62ba9b7b4c1cafa69179
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:6dfa9794ba29af703db8f972039c8c9dd122e2249b827ee0121220c833ddeaec
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
