apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:c6b7043b7ae9accb9710404e505116c76da30cba551c1c9d2d3f5cb93f726648
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:f1ba24eee83ade73696a4e5d98f652e148e0a41dc46dd0fb2f42969d30c09ba2
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
