apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:30a8e654a5ab252da5bc92461c2ce12b8541bc5a4440f7b4d28c780502ce518b
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:d40f21247e18b04abb948948739a847548569326d1020ba169564832841ebde4
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
