apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:6f8341f38b438d18f90fdb1a6ddf0df5089df7a24f14488541752cdf3f19e690
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:fdebc75ae3b34388ecde014a1c88752cefb0a3fa43453ea44b749e5016f82a08
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
