apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../monitoring
images:
- name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
