apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:120cef77251fb63bc2696d9ffebc6651b49c5ca6358a3058728e2bc4aa269de1
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:ddae3d27e1eb75136fbf08e86c9bd210917d864d57282ad00cd32407c1932a02
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
