apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:33d06787bb53f0704b26cdac1c7178a8180d17cdde4b665e9bbd1ee9067f0e82
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:3ce923d72774914cc396b934c5b834cbdd40478b295f8eae785b5a8d0fcc1647
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
