apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  digest: sha256:ffd5312e645d9a86ab5f97e2bdc3864b8b9665f61f2204497e26c160a8b794a3

- name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
  digest: sha256:a1519185d544354c78dd4629e787a667b5968ae7eccdf4204ee10fb270078de3