apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:22c841a82938f855878c1d0a3fb79cd1225fe9d0f4b0a9349540f07b16098405
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:a7eaa3814f6fe2d061c4860f3dbdbb401894c1b37a016eafc48ca5b89511aa6e
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
