apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:afbf5f4ede56db33f89c4645f55a9ef2841a37ddd900bd9353091a3c3c32ccb8
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:4260de36a616d7d8e4cc87d1a36d26cf54e6f7ecad693c636d38134de4772974
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
