apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- deployment.yaml
- service.yaml


images:
- name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newTag: dev
- digest: sha256:66fa2641c9cea787e8bb9926fd48a6054a5ed4cb2fdd4cde81ccfc2bedc8e826
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
