apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- deployment.yaml
- service.yaml


images:
- name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newTag: dev
- digest: sha256:aaec50b491d700d4944e84309c66960be95d8d6a9120d9a7e03527ac1625c464
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
