apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
- deployment.yaml
- service.yaml
images:
- digest: sha256:45d8b595afd44447e4585ea641f1d86ec675913bc5db23d93c554d3cfa5dacb2
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
