apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
- deployment.yaml
- service.yaml
images:
- digest: sha256:b0e67d0692034c03dca9040f43ab450462127f7100fc103d200d7284b8fe2e4c
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
