apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- deployment.yaml
- service.yaml


images:
- name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
  newTag: dev
- digest: sha256:ac5e3d44ba5a86c4fe2198319d22f95a4a8adac7cd215b9a4381f35e322a606b
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
