apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
- deployment.yaml
- service.yaml
images:
- digest: sha256:8b6ed855d5c6f3d2ffdfb98d62cfc21feae90643451eca361edf2b61b0eeb093
  name: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
