apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  namespace: demo-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: demo.local
    http:
      paths:
      # ======================
      # Backend API
      # ======================
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000

      # ======================
      # Swagger
      # ======================
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000

      # ======================
      # Frontend React
      # ======================
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
