apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
  - namespace.yaml
  - backend
  - frontend

# ðŸ”½ MUY IMPORTANTE
namespaceTransformer:
  - include: false
